name: analytics_engineering_service_mart
version: "0.2.0"
config-version: 2

require-dbt-version: [">=1.11.0", "<1.13.0"]

profile: analytics_engineering_service_mart

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  report_date: "2026-06-19"
  event_lookback_days: 7

models:
  analytics_engineering_service_mart:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  analytics_engineering_service_mart:
    +schema: raw
